### ISSUE TITLE
New API for APIs.io

### ISSUE THREAD

**Issue by picsoung** [apisio/apis.io#9]
Here is the place for a discussion about what you want to see in the new APIs.io 's API.

The current documentation could be found [here](http://apis.io/api)

What I had in mind to add:
- pagination on results
- a `search` endpoint, to search for apis the same way that on the site
- clarify `ping` endpoint
- add optional `fields` param to ask for particular fields
- add `offset`,`limit`

Any other thoughts and stuff that you want to see in it?

**Comment by amanda-hua** [comment]
Hi, I am seeing the following errors after updating the keys in settings_tpl.json and running meteor update

W20150113-20:43:47.238(-8)? (STDERR)          
W20150113-20:43:47.307(-8)? (STDERR) /Users/john/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150113-20:43:47.307(-8)? (STDERR) 						throw(ex);
W20150113-20:43:47.307(-8)? (STDERR) 						      ^
W20150113-20:43:47.307(-8)? (STDERR) TypeError: Object #<Object> has no method 'describe'
W20150113-20:43:47.307(-8)? (STDERR)     at app/server/packages/npm-container/package.js:4:11
W20150113-20:43:47.308(-8)? (STDERR)     at app/server/packages/npm-container/package.js:23:3
W20150113-20:43:47.308(-8)? (STDERR)     at /Users/john/git/apis.io.git/trunk/.meteor/local/build/programs/server/boot.js:175:10
W20150113-20:43:47.308(-8)? (STDERR)     at Array.forEach (native)
W20150113-20:43:47.308(-8)? (STDERR)     at Function._.each._.forEach (/Users/john/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150113-20:43:47.308(-8)? (STDERR)     at /Users/john/git/apis.io.git/trunk/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
W20150113-20:43:49.263(-8)? (STDERR)          
W20150113-20:43:49.264(-8)? (STDERR) /Users/john/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150113-20:43:49.265(-8)? (STDERR) 						throw(ex);
W20150113-20:43:49.265(-8)? (STDERR) 						      ^
W20150113-20:43:49.265(-8)? (STDERR) TypeError: Object #<Object> has no method 'describe'
W20150113-20:43:49.265(-8)? (STDERR)     at app/server/packages/npm-container/package.js:4:11
W20150113-20:43:49.265(-8)? (STDERR)     at app/server/packages/npm-container/package.js:23:3
W20150113-20:43:49.265(-8)? (STDERR)     at /Users/john/git/apis.io.git/trunk/.meteor/local/build/programs/server/boot.js:175:10
W20150113-20:43:49.266(-8)? (STDERR)     at Array.forEach (native)
W20150113-20:43:49.266(-8)? (STDERR)     at Function._.each._.forEach (/Users/john/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150113-20:43:49.266(-8)? (STDERR)     at /Users/john/git/apis.io.git/trunk/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
W20150113-20:43:51.173(-8)? (STDERR)          
W20150113-20:43:51.174(-8)? (STDERR) /Users/john/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150113-20:43:51.175(-8)? (STDERR) 						throw(ex);
W20150113-20:43:51.175(-8)? (STDERR) 						      ^
W20150113-20:43:51.175(-8)? (STDERR) TypeError: Object #<Object> has no method 'describe'
W20150113-20:43:51.175(-8)? (STDERR)     at app/server/packages/npm-container/package.js:4:11
W20150113-20:43:51.175(-8)? (STDERR)     at app/server/packages/npm-container/package.js:23:3
W20150113-20:43:51.175(-8)? (STDERR)     at /Users/john/git/apis.io.git/trunk/.meteor/local/build/programs/server/boot.js:175:10
W20150113-20:43:51.175(-8)? (STDERR)     at Array.forEach (native)
W20150113-20:43:51.176(-8)? (STDERR)     at Function._.each._.forEach (/Users/john/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150113-20:43:51.176(-8)? (STDERR)     at /Users/john/git/apis.io.git/trunk/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

Any suggestions?
